# Generated by Django 5.0.2 on 2024-03-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripyion',
            new_name='descripion',
        ),
    ]
