# Generated by Django 5.0.2 on 2024-03-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_descripyion_product_descripion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripion',
            new_name='description',
        ),
    ]
